language: java
jdk:
 - oraclejdk8
sudo: false

addons:
  sonarcloud:
    organization: "crejczyk-github"
    token:
      secure: "4a8649d749104fceb64331b6f7c4244d2712b07e"
      
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    
install: true

services: mongodb
script: "mvn test -B"

after_success:
  - mvn clean verify -Pjacoco org.eluder.coveralls:coveralls-maven-plugin:report sonar:sonar