language: java
jdk:
 - oraclejdk8
sudo: false

addons:
  sonarcloud:
    organization: "crejczyk-github"
    token:
      secure: "4a8649d749104fceb64331b6f7c4244d2712b07e"
      
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    
install: true

services: mongodb
script: "mvn test -B"

after_success:
 - mvn sonar:sonar -Dsonar.organization=crejczyk-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=8a8d1cef333dd947418ef45e316b2fa839ed2574